services:

  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB=interkom
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  interkom-server:
    build: ./
    image: interkom-server
    container_name: interkomServer
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/interkom
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - ${WEB_PORT}:8080
    restart: unless-stopped
    depends_on: 
      - database

volumes:
  pgdata:
